// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8v404ShCVz2rdm3N0zdCXvEEHpFF-Q0',
    appId: '1:694566494000:web:edc84ff5b09549233d72f5',
    messagingSenderId: '694566494000',
    projectId: 'shopke-4b83a',
    authDomain: 'shopke-4b83a.firebaseapp.com',
    storageBucket: 'shopke-4b83a.firebasestorage.app',
    measurementId: 'G-SBK5302Q84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9n9jv6Uu3NiMxLolkyzhUlRfY70dkMVQ',
    appId: '1:694566494000:android:6191b0ca76a2e1bb3d72f5',
    messagingSenderId: '694566494000',
    projectId: 'shopke-4b83a',
    storageBucket: 'shopke-4b83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalqlzntkmbb9fglMm4MqEnJ6cE-kfsPs',
    appId: '1:694566494000:ios:a7d77eea849e7fe83d72f5',
    messagingSenderId: '694566494000',
    projectId: 'shopke-4b83a',
    storageBucket: 'shopke-4b83a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalqlzntkmbb9fglMm4MqEnJ6cE-kfsPs',
    appId: '1:694566494000:ios:a7d77eea849e7fe83d72f5',
    messagingSenderId: '694566494000',
    projectId: 'shopke-4b83a',
    storageBucket: 'shopke-4b83a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD8v404ShCVz2rdm3N0zdCXvEEHpFF-Q0',
    appId: '1:694566494000:web:80ab9d751dd6ca873d72f5',
    messagingSenderId: '694566494000',
    projectId: 'shopke-4b83a',
    authDomain: 'shopke-4b83a.firebaseapp.com',
    storageBucket: 'shopke-4b83a.firebasestorage.app',
    measurementId: 'G-H580F3T0YN',
  );
}
